In [1]:
import numpy as np

In [20]:
X = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]])
X

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [21]:
X.shape

(6, 3)

In [24]:
X.reshape(2, -1)

array([[1, 2, 3, 4, 5, 6, 1, 2, 3],
       [4, 5, 6, 1, 2, 3, 4, 5, 6]])

In [33]:
X[2]

array([1, 2, 3])

In [45]:
w = np.random.randint(1, 5)
np.random.randint(1, 100, size=(w, 2))

array([[45, 26],
       [52, 40]])

In [67]:
x=np.array([[1,2],[3,4]], dtype=np.float64)
y=np.array([[5,6],[7,8]], dtype=np.float64)

np.eye(5)*4

array([[4., 0., 0., 0., 0.],
       [0., 4., 0., 0., 0.],
       [0., 0., 4., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 4.]])

# Checkpoint

In [71]:
class Point3D:
    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z
        
    def __repr__(self):
        return "({}, {}, {})".format(self.x, self.y, self.z)
        
p = Point3D(1, 2, 3)
print(p)

(1, 2, 3)


In [75]:
class Circle:
    def __init__(self, center, radius):
        self.center = center
        self.radius = radius
    
    def perimeter(self):
        return (self.radius*2)*np.pi
    
    def area(self):
        return (self.radius**2)*np.pi
    
    def isInside(self, A):
        dist = 0
        for c1, c2 in zip(self.center, A): #Pour parcourir les coordonnées des deux points en parallèle (x avec x et y avec y)
            dist += (c1 - c2)**2
        return np.sqrt(dist) < self.radius #Si la racine de la distance est inférieure au rayon, retourner true car le point est danss le cercle

C = Circle((0, 0), 1)
print(C.area())
print(C.perimeter())
print(C.isInside((.5, .5)))

3.141592653589793
6.283185307179586
True


In [ ]:
#Bank account